# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vencedores de Sangrar
description: >- # this means to ignore newlines until "baseurl:"
  Una novela de misterio ambientada en Perú que explora temas de poder, corrupción y justicia.
baseurl: "/Vencedores-de-Sangrar" # el subpath de tu sitio para GitHub Pages
url: "https://carlosvidal.github.io" # reemplaza con tu nombre de usuario de GitHub
lang: es

# Build settings
# Usar tema remoto de GitHub (Hitchens)
remote_theme: patdryburgh/hitchens
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Configuración del sitio
show_excerpts: false
hide_search: true
minima:
  date_format: "%d-%m-%Y"

# Información del autor
author:
  name: Carlos Vidal
  email: carlos@mitienda.pe

# Estilos personalizados
sass:
  sass_dir: _sass
  style: compressed

# Archivos adicionales a incluir
include:
  - assets/css/custom.css

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - capitulo-01/
  - capitulo-02/
  - capitulo-03/
  - capitulo-04/
  - capitulo-05/
  - capitulo-06/
  - capitulo-07/
  - capitulo-08/
  - capitulo-09/
  - capitulo-10/
  - capitulo-11/
  - capitulo-12/
  - capitulo-13/
  - capitulo-14/
  - capitulo-15/
  - capitulo-16/
  - capitulo-17/
  - capitulo-18/
  - capitulo-19/
  - capitulo-20/
  - capitulo-21/
  - capitulo-22/
  - capitulo-23/
  - capitulo-24/
  - capitulo-25/
  - capitulo-26/
  - capitulo-27/
  - capitulo-28/
  - capitulo-29/
  - capitulo-30/
  - capitulo-31/
  - capitulo-32/
  - capitulo-33/
  - capitulo-34/
  - capitulo-35/
  - capitulo-36/
  - capitulo-37/
  - capitulo-38/
  - capitulo-39/
  - capitulo-40/
  - reorganize.py
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
